CREATE TABLE IF NOT EXISTS `{project}.{dataset}.pipeline_runs` (
  run_id          STRING    NOT NULL OPTIONS(description="UUID4 run identifier"),
  status          STRING    NOT NULL OPTIONS(description="queued | running | succeeded | failed"),
  triggered_by    STRING,
  trigger_source  STRING,
  jobs_path       STRING,
  config_path     STRING,
  created_at      TIMESTAMP NOT NULL,
  started_at      TIMESTAMP,
  finished_at     TIMESTAMP,
  total_jobs      INT64,
  passed_filter   INT64,
  ranked          INT64,
  cvs_generated   INT64,
  error_message   STRING,
  error_stage     STRING    OPTIONS(description="stage name where the run failed"),
  effective_settings_json STRING    OPTIONS(description="Merged config snapshot at trigger time"),
  results_export_json STRING OPTIONS(description="Immutable run-results export snapshot for completed runs"),
  cv_generation_debug_json STRING OPTIONS(description="Immutable run-scoped CV-generation debug snapshot for completed runs"),
  stage_transition_artifacts_json STRING OPTIONS(description="Immutable run-scoped stage transition artifacts snapshot for completed runs"),
  settings_used_json STRING OPTIONS(description="Immutable run-scoped effective-settings snapshot for completed runs"),
  mapping_suggestions_json STRING OPTIONS(description="Immutable run-scoped mapping suggestions snapshot"),
  run_mode        STRING    OPTIONS(description="run_all | manual_staged"),
  checkpoint_status STRING  OPTIONS(description="Manual checkpoint lifecycle status"),
  next_stage      STRING    OPTIONS(description="Next stage to execute for manual staged runs"),
  last_completed_stage STRING OPTIONS(description="Most recently completed stage for manual staged runs"),
  completed_stages_json STRING OPTIONS(description="JSON array of completed pipeline stages"),
  checkpoint_payload_json STRING OPTIONS(description="Serialized checkpoint payload for manual stage continuation"),
  -- lifecycle controls
  queue_job_id          STRING    OPTIONS(description="RQ job id for queued run cancellation"),
  cancel_requested_at   TIMESTAMP,
  cancel_requested_by   STRING,
  archived_at           TIMESTAMP,
  archived_by           STRING
);
