skill_synonyms:
  3nf: third normal form (3nf)
  about you: about you advertising
  advanced analytics tools: advanced analytics
  advanced excel: microsoft excel
  advanced excel skills: microsoft excel
  advanced excel skills required: microsoft excel
  advanced financial analysis: financial analysis
  advanced ms excel skills: microsoft excel
  advanced predictive modelling: predictive modelling
  advanced proficiency in sql: sql
  agile projektmanagement-methoden: agile project management
  ahrefs/semrush: ahrefs
  ai-supported productivity tools: ai productivity tools
  airflow: apache airflow
  akzeptanzkriterien: acceptance criteria
  amazon: amazon advertising
  analysen & kpis: kpi analysis
  analysieren die geschäftsprozesse: business process analysis
  analysierst tiefgreifend unit economics: unit economics analysis
  analysing conversion funnels: conversion funnel analysis
  analysis of performance: marketing analytics
  and powerpoint: microsoft powerpoint
  anspruch an "clean code": clean code
  api businesses: api platforms
  arbeit mit excel: microsoft excel
  architecting complex data models: data modeling
  as400 von vorteil: ibm as/400
  assisting in data preparation: data preparation
  attribution tooling: marketing attribution
  audio: audio technology
  ausrichtung auf budget-vorgaben: budget management
  auswertungen und analysen: data analysis
  aws: amazon web services
  azure: microsoft azure
  backend-anwendungen: backend development
  background in content moderation: content moderation
  background in quality assurance: quality assurance (qa)
  basic knowledge of javascript: javascript
  basic knowledge of linux: linux
  betreuung von m&a-projekten: mergers & acquisitions (m&a)
  betriebs- / finanzmodelle: financial modeling
  bevorzugt ms business central: microsoft dynamics 365 business central
  big query: google bigquery
  bigquery: google bigquery
  bigquery ml: machine learning
  build and maintain dashboards: dashboarding
  build and update reports: reporting
  build dashboards: dashboard building
  building and maintaining dashboards: dashboarding
  building entity attribution: entity attribution
  business central: dynamics 365 business central
  businessrelevanter kpis und metriken: kpi analysis
  capitaliq: capital iq
  carve-outs: carve-out
  champion accurate product costing: product costing
  ci/cd pipelines: ci/cd
  clear reporting through dashboards: dashboard reporting
  clustering: sql server clustering
  comfort with scenario analysis: scenario analysis
  commissioning: plant commissioning
  conduct industry analysis reports: industry analysis
  conduct market research: market research
  conduct research: research
  continuously improve ... roi: roi optimization
  continuously improve conversion: conversion rate optimization
  contribute to cro initiatives: cro
  control towers: supply chain control tower
  coordinate business due diligence: due diligence
  core banking integrations: core banking integration
  corporate pitch decks: pitch deck design
  corporate valuation methods: corporate valuation
  create dashboards and reports: dashboarding
  create execution roadmaps: project roadmap planning
  create process models: process modeling
  create user requirement specifications: requirements specification
  creating self-service analytics: self-service analytics
  creation of jira workflows: jira
  data and financial analysis: financial analysis
  data modeling experience: data modeling
  data modelling principles: data modelling
  data vault und 3nf: data vault
  datenmodellierung: data modeling
  datenvisualisierung: data visualization
  dbt core: dbt
  deal structures: deal structuring
  debugging discrepancies: debugging
  deep content seo expertise: seo
  define go-to-market strategies: go-to-market strategy
  define target operating models: target operating model (tom)
  defining testing strategies: test strategy
  derivatives pricing theory: derivatives pricing
  design and execute campaigns: campaign management
  developing critical dashboards: dashboarding
  developing functional test cases: test case design
  digital social media kits: social media asset design
  digital strategies: digital marketing strategy
  digital-kampagnen: digital campaign management
  distinct color palettes: color palette development
  dokumentation von änderungen: documentation
  du analysierst relevante kpis: kpi analysis
  du ermittelst wirtschaftlich berechtigte: ubo identification
  du erstellst fachliche anforderungen: requirements engineering
  du erstellst instagram-posts: instagram marketing
  du erstellst monatliche reportings: financial reporting
  du führst kosten-nutzen-analysen durch: cost-benefit analysis
  du kennst reverse etl: reverse etl
  du übernimmst eigenständig bookings: influencer booking
  durchführung von ad-hoc-analysen: ad hoc analysis
  durchführung von uat: user acceptance testing (uat)
  einmeldung der sicherheiten: collateral reporting
  email: email marketing
  end-to-end business analysis: business analysis
  end-to-end campaign execution: campaign execution
  ensuring data quality: data quality
  entwickelst darauf produktive dashboards: dashboard-entwicklung
  erfahrung im bereich analytics: analytics
  erfahrung im partner management: partner management
  erfahrung im schnittstellen-design: interface design
  erfahrung mit datev wünscheswert: datev
  erfahrung mit docker: docker
  erfahrung mit erp-systemen: erp systems
  erfahrungen im anforderungsmanagement: requirements management
  erfahrungen im software-testing: software testing
  erste berührungen im markenrecht: trademark law
  erste erfahrung im projektmanagement: project management
  erstellen von dashboards: dashboarding
  erstellst du budgets: budgeting
  erstellung von forecasts: forecasting
  erstellung von präsentationen: präsentationserstellung
  erstellung von unternehmensbewertungen: valuation
  erstellung von user-stories: user stories
  especially excel: microsoft excel
  especially in excel: microsoft excel
  establish forecasting methodologies: forecasting
  evaluate pricing: pricing analysis
  evaluating requirements: requirements analysis
  excel: microsoft excel
  experience building partner programs: partner program management
  experience in ai: artificial intelligence
  experience in digital marketing: digital marketing
  experience in erp systems: erp systems
  experience in financial modeling: financial modeling
  experience in java: java
  experience performing fit-gap analysis: fit-gap analysis
  experience with .docx files.: docx
  experience with automation: automation
  experience with cognos tm1: ibm cognos tm1
  experience with data analysis: data analysis
  experience with mifid ii: mifid ii
  experience with mifir: mifir
  experience with process design: process design
  experience with quality assurance: quality assurance (qa)
  experience with visualization tools: data visualization tools
  familiarity with ... databases: databases
  familiarity with ... excel: microsoft excel
  familiarity with apple products: apple products
  familiarity with data cleaning: data cleaning
  familiarity with data modeling: data modeling
  familiarity with data structures: data structures
  familiarity with developer tools: developer tools
  familiarity with financial modelling: financial modeling
  familiarity with iot systems: iot
  familiarity with salesforce: salesforce
  familiarity with visualization tools: data visualization
  financial modelling skills: financial modeling
  financial models: financial modeling
  finanzmodellierungsfähigkeiten: financial modeling
  flatfiles: flat files
  flowcharts: flowcharting
  focus on causal analysis: causal analysis
  focus on lead generation: lead generation
  follow red-teaming protocols: red teaming
  forecast company kpis: kpi forecasting
  fortgeschrittene excel-kenntnisse: microsoft excel
  fundierte sap mm kenntnisse: sap mm
  führst ad-hoc-analysen durch: ad hoc analysis
  ga4: google analytics 4
  gcp: google cloud
  gemini: genai
  gemäß bestehender playbooks: incident response playbooks
  generative ai security challenges: generative ai security
  git / github: git
  github: git
  go-to-market: go-to-market strategy
  good knowledge of excel: microsoft excel
  good knowledge of hgb: hgb
  google analytics (ga4): google analytics
  google cloud platform: google cloud
  graphana: grafana
  grundkenntnisse in ... premiere: adobe premiere
  grundkenntnisse in ... sharepoint: microsoft sharepoint
  grundkenntnisse in linux: linux
  grundkenntnisse in ms excel: microsoft excel
  grundkenntnisse in photoshop: adobe photoshop
  grundlegende kenntnisse in statistik: statistics
  grundverständnis von datenanalyse: data analysis
  grundverständnis von datenarchitektur: data architecture
  grundverständnis von datenmodellierung: data modeling
  gtm strategy: go-to-market (gtm) strategy
  gute kenntnisse in datenanalyse: data analysis
  hands-on campaign management experience: campaign management
  hands-on experience in looker: looker
  heatmaps: heatmap analytics
  hubspot or equivalent crm/ma: crm
  hyperion o.ä.: oracle hyperion
  idealerweise erfahrung mit bloomreach: bloomreach
  ideally hubspot: hubspot
  idealweise im programmatic advertising: programmatic advertising
  idealweise motion design: motion design
  ifrs familiarity is advantageous: ifrs
  im besonderen ... t-sql: t-sql
  im besonderen c#: c#
  im requirements engineering: requirements engineering
  im testmanagement: test management
  im umgang mit visualisierungstools: data visualization tools
  impact-analysen: impact analysis
  implement a/b testing: a/b testing
  improve roas and margin: roas optimization
  inbound: inbound marketing
  including scalable logos: logo design
  initial experience with python: python
  inklusive kommentierung von abweichungen: variance analysis
  insbesondere excel: microsoft excel
  instrument the funnel: funnel instrumentation
  intelligent document management: document management
  intelligent workflow automation: workflow automation
  into cohesive gtm programs: go-to-market (gtm)
  it-projektmanagement: it project management
  itil-prozessen: itil
  jira usage.: jira
  k8s: kubernetes
  kafka: apache kafka
  kenntnisse in der datenbankmodellierung: data modeling
  kenntnisse in linux-systemen: linux
  knowledge of cost accounting: cost accounting
  knowledge of seo/geo basics: geo
  kohorten-analysen: cohort analysis
  komplexes prozess-design: process design
  konzernrechtliche fragestellungen: konzernrecht
  kpi-definitionen: kpi definition
  kreativitätstechniken: creativity techniques
  landing pages: landing page optimization
  large language models: genai
  leading a marketing team: marketing team leadership
  leverage ... alternative datasets: alternative data analysis
  leverage artificial intelligence: artificial intelligence
  llm: genai
  llms: genai
  looker studio: looker
  lookerstudio: looker
  low-code/no-code platforms: low-code development
  maintaining automated regression tests: automated regression testing
  maintaining kpi dashboards: dashboarding
  managing pipelines: pipeline management
  managing the product backlog: product backlog management
  margin impact: margin analysis
  meta: meta ads
  meta library: meta ad library
  metabase power user: metabase
  mica-related compliance preparation: mica compliance preparation
  ml: machine learning
  mlops practices: mlops
  model deployment workflows: model deployment
  moderation von workshops: workshop facilitation
  modern bi tools: business intelligence (bi) tools
  monitoring data quality: data quality monitoring
  nlp: natural language processing
  nosql-datenbanksystemen: nosql databases
  oder datengetriebenen workflows: datengetriebene workflows
  oder video-editing: video-editing
  oder von sap s/4hana: sap s/4hana
  ooh: out-of-home advertising
  optimization: process optimization
  otto: otto advertising
  outbound: outbound marketing
  paid social: paid social advertising
  partitioning strategies: data partitioning
  perform in-depth industry research: industry research
  perform quantitative analysis: quantitative analysis
  performance-dashboards: dashboarding
  performs basic statistical analysis: statistical analysis
  personal care product manufacturing: beauty / personal care
  pg: postgresql
  postgres: postgresql
  power automate: microsoft power automate
  power bi: microsoft power bi
  power point: microsoft powerpoint
  powerbi: microsoft power bi
  powerpoint: microsoft powerpoint
  predict and analyze earnings: earnings forecasting
  print materials: print design
  process modelling: process modeling
  processing technical tickets: ticket handling
  product launch activations: product launch activation
  production of high-quality biochar: biochar production
  produktive erfahrung mit dbt: dbt
  proficiency in excel: microsoft excel
  proficiency in python preferred: python
  proficient in excel: microsoft excel
  proficient in microsoft powerpoint: microsoft powerpoint
  project management through data: project management
  promotion-projekte: promotion-management
  prompt engineering: genai
  providing second-level support: second-level support
  prozessdokumentationen: process documentation
  prüfung von screeningtreffern: sanctions screening alert review
  pull salesforce reports: salesforce
  py: python
  python is an advantage: python
  quality assurance: quality assurance (qa)
  quantitative modelling: quantitative modeling
  rag: retrieval-augmented generation (rag)
  real-time planning dashboards: real-time dashboards
  redshift: amazon redshift
  refining event structures: event tracking
  relationalen ... datenbanksystemen: relational databases
  replication: sql server replication
  reportings an die bafin: regulatory reporting
  revenue forecasts: revenue forecasting
  run email marketing campaigns: email marketing
  running demos: sales demos
  running multi-channel campaigns: multi-channel campaign management
  sales-controlling: sales controlling
  sap erfahrung von vorteil: sap
  sap idocs: sap idoc
  search: search marketing
  sehr gute excel kenntnisse: microsoft excel
  sehr gutes kpi-verständnis: kpi analysis
  set okrs: okrs
  sharepoint: microsoft sharepoint
  sicher mit ms office: microsoft office
  sicherer umgang mit erp-systemen: erp systems
  sicherer umgang mit excel: microsoft excel
  sicherer umgang mit ms-office: microsoft office
  sicherer umgang mit powerpoint: microsoft powerpoint
  sla familiarity: service level agreements (sla)
  soc 1st level analysis: security operations center (soc)
  social media ads: social media advertising
  software development and it services and it consulting: design software
  solid project management skills: project management
  solide statistik-kenntnisse: statistical analysis
  sound sap mm knowledge.: sap mm
  sowie erfahrung mit bait: bait
  sowie jira und confluence: confluence
  sowie sap: sap
  spark: apache spark
  speech: speech technology
  splunk es: splunk enterprise security
  sql: structured query language
  sql-/sap-kenntnisse sind von vorteil: sap
  stakeholder workshops: workshop facilitation
  startup valuation methods: startup valuation
  stellst du datenqualität sicher: data quality
  strong command of sql: sql
  strong data analysis skills: data analysis
  strong financial modelling capabilities: financial modeling
  strong ms office skills: microsoft office
  strong sql skills: sql
  support change management processes: change management
  support pricing analysis: pricing analysis
  supporting mvp deliveries: mvp delivery
  systemanalyse: system analysis
  systemintegration: system integration
  teams: microsoft teams
  testing & skalierung: campaign scaling
  testmanagement & qualitätssicherung: quality assurance (qa)
  thomson / reuters: thomson reuters
  tools such as excel: microsoft excel
  tools wie sap signavio: sap signavio
  trendscouting: trend scouting
  troubleshooting: process troubleshooting
  troubleshooting system issues: troubleshooting
  typography systems: typography system design
  umgang mit bais: bais
  umgang mit idh: idh
  umgang mit medizinischen terminologien: medical terminologies
  umgang mit ms office: microsoft office
  umgang mit s-ibus: s-ibus
  umgang mit vba: vba
  umsetzung von test‑&‑learn‑ansätzen: test-and-learn experimentation
  und bloomberg: bloomberg terminal
  und datenvisualisierung: data visualization
  unternehmensbewertungen: company valuation
  unternehmensrecherchen: company research
  unterstützt die qualitätssicherung: quality assurance (qa)
  unterstützung bei m&a transaktionen: m&a
  uphold data governance: data governance
  using agile methods: agile methodologies
  ux/ui: ux/ui design
  validating data accuracy: data validation
  vector databases: genai
  verstehst datenflüsse: datenflüsse
  vertex ai: genai
  visio: microsoft visio
  von der vertraulichkeitsvereinbarung: non-disclosure agreement (nda)
  von rest-apis: rest apis
  webanalyse mit google analytics: google analytics
  weitere hr saas-systeme: hr saas
  wie bspw. google dv360: google dv360
  wirtschaftlichkeits- und risikoanalysen: risk analysis
  work with spreadsheets: spreadsheets
  z. b. ms access: microsoft access
  z. b. pmp: pmp
  z. b. scrum: scrum
  z.b. c4c: sap cloud for customer (c4c)
  z.b. sac: sap analytics cloud (sac)
  zalando: zalando advertising
  über die due diligence: due diligence
  überwachst kreditrisiken aufmerksam: credit risk monitoring
  „anforderungsmanagement“: requirements management
